CREATE PROCEDURE [dbo].[USP_LOGIN_SXZ]
@USERID VARCHAR (50),
@PASSWORD VARCHAR (32),
@RESULT CHAR (4) OUTPUT
AS
BEGIN
	SET NOCOUNT ON   
	DECLARE @PWD VARCHAR(50)
	DECLARE @ACCOUNTID INT

	--初始化设置返回值为'0000'
	SELECT @RESULT = '0000'

	--更新账户冻结信息,如更新错误则返回'0001'
	BEGIN TRANSACTION USP_LOGIN_SXZ

	SELECT @ACCOUNTID = ACCOUNTID, @PWD = PASSWORD FROM TBL_ACCOUNT WHERE ACCOUNT = @USERID
	IF @@ROWCOUNT = 0
		SET @RESULT = '0001'
	ELSE

	IF @RESULT = '0000'
	BEGIN
		IF dbo.UFN_MD5(@PASSWORD)<>@PWD
		BEGIN
			SET @RESULT = '0002'
		END
	END

   IF @RESULT = '0000'
      COMMIT TRANSACTION USP_LOGIN_SXZ
   ELSE 
      ROLLBACK TRANSACTION USP_LOGIN_SXZ

	SELECT @RESULT AS '@RESULT',@ACCOUNTID
END


