-- =============================================
-- Author:		<Daniel>
-- Create date: <2012-04-11>
-- Description:	<激活大区游戏>
-- =============================================
CREATE PROCEDURE [dbo].[USP_ACTIVATEGAME]
@USERID			VARCHAR (50),		--官网帐号名
@PASSWORD		VARCHAR (32),		--帐号密码
@REGISTERTS		DATETIME			--帐号注册时间
AS
BEGIN
	SET NOCOUNT ON
	SET XACT_ABORT ON
	DECLARE @RESULT CHAR(4)
	DECLARE @ACCOUNTID INT
	SET @ACCOUNTID = -1
	--初始化设置返回值为'0000'
	SELECT @RESULT = '0000'

	--判断帐号是否已经激活
	IF @RESULT = '0000' AND EXISTS(SELECT 1 FROM TBL_ACCOUNT A  WHERE A.ACCOUNT = @USERID )
	BEGIN
		SET @RESULT = '0002'
	END

	IF @RESULT = '0000'
	BEGIN
		--开始事务
		BEGIN TRANSACTION ACTIVATEGAME
		
		SELECT @ACCOUNTID = A.ACCOUNTID FROM TBL_ACCOUNT A WHERE A.ACCOUNT = @USERID
		IF @@ROWCOUNT = 0
		BEGIN
			--开始插入帐号信息
			INSERT INTO TBL_ACCOUNT(ACCOUNT,[PASSWORD],REGISTERDATE)		
				SELECT @USERID,dbo.UFN_MD5(@PASSWORD),@REGISTERTS
			IF @@ERROR = 0
			BEGIN
				SET @ACCOUNTID = @@IDENTITY
			END
			ELSE
			BEGIN
				SET @RESULT = '0003'
			END
		END

		IF @RESULT = '0000'
		BEGIN
			COMMIT TRANSACTION ACTIVATEGAME
		END
		ELSE
		BEGIN
			ROLLBACK TRANSACTION ACTIVATEGAME
		END
	END

	SELECT @RESULT, @ACCOUNTID
END
