-- =============================================
-- Author:		<Daniel>
-- Create date: <2012-04-11>
-- Description:	<激活大区游戏>
-- =============================================
CREATE PROCEDURE [dbo].[USP_ACTIVATEGAMEAPPLE]
@USERID			VARCHAR (50),		--官网帐号名
@PASSWORD		VARCHAR (32)
AS
BEGIN
	SET NOCOUNT ON
	SET XACT_ABORT ON
	DECLARE @RESULT CHAR(4)
	DECLARE @ACCOUNTID INT
	SET @ACCOUNTID = -1
	--初始化设置返回值为'0000'
	SELECT @RESULT = '0000'

	IF @RESULT = '0000'
	BEGIN
		--开始事务
		BEGIN TRANSACTION ACTIVATEGAME
		
		--开始插入帐号信息
		INSERT INTO TBL_ACCOUNT(ACCOUNT,[PASSWORD],REGISTERDATE)		
			SELECT @USERID,dbo.UFN_MD5(@PASSWORD),GETDATE()
		IF @@ERROR = 0
		BEGIN
			SET @ACCOUNTID = @@IDENTITY
		END

		IF @RESULT = '0000'
		BEGIN
			COMMIT TRANSACTION ACTIVATEGAME
		END
		ELSE
		BEGIN
			ROLLBACK TRANSACTION ACTIVATEGAME
		END
	END

	SELECT @RESULT, @ACCOUNTID
END
