/****** 对象:  Table [dbo].[TBL_ACCOUNT]    脚本日期: 04/06/2014 16:29:50 ******/
CREATE PROCEDURE [dbo].[USP_BINDACCOUNT_SXZ]
@USERID			VARCHAR (50),		--官网帐号名
@PASSWORD		VARCHAR (32),		--帐号密码
@ACCOUNTID		INT
AS
BEGIN
	SET NOCOUNT ON
	SET XACT_ABORT ON
	DECLARE @Error INT
	SET @Error = 5--1没找到账号，2是改变名字数据库操作出错，3不能在改变名字, 5账号重名
	DECLARE @ACCOUNTNAME VARCHAR(50)
	SET @ACCOUNTNAME = ''

	
	BEGIN TRANSACTION BINDACCOUNT_SXZ	
	SELECT @ACCOUNTNAME = ACCOUNT FROM TBL_ACCOUNT WHERE ACCOUNTID = @ACCOUNTID
	IF @@ROWCOUNT <> 0
	BEGIN
		IF @ACCOUNTNAME = ''
		BEGIN
			IF NOT EXISTS(SELECT 1 FROM TBL_ACCOUNT WHERE ACCOUNT = @USERID)
			BEGIN
				UPDATE TBL_ACCOUNT SET ACCOUNT = @USERID, PASSWORD = dbo.UFN_MD5(@PASSWORD) WHERE ACCOUNTID = @ACCOUNTID
				IF @@ROWCOUNT <> 0
				BEGIN
					SET @Error = 0
					COMMIT TRANSACTION BINDACCOUNT_SXZ
				END
				ELSE
				BEGIN
					SET @Error = 2
					ROLLBACK TRANSACTION BINDACCOUNT_SXZ
				END
			END
			ELSE
			BEGIN
				SET @Error = 5
				ROLLBACK TRANSACTION BINDACCOUNT_SXZ
			END
		END
		ELSE
		BEGIN
			SET @Error = 3
			ROLLBACK TRANSACTION BINDACCOUNT_SXZ
		END
	END
	ELSE
	BEGIN
		SET @Error = 1
		ROLLBACK TRANSACTION BINDACCOUNT_SXZ
	END

	SELECT @Error
END