CREATE TABLE [dbo].[TBL_USERITEM] (
    [ACCOUNTID]   INT         NOT NULL,
    [ROLEID]      BIGINT      NOT NULL,
    [ITEMUNIQUE]  VARCHAR (2) NOT NULL,
    [ITEMNUM]     INT         NOT NULL,
    [RECEIPTNUM]  INT         NOT NULL,
    [CREATEDATE]  DATETIME    NOT NULL,
    [RECEIPTTYPE] TINYINT     NOT NULL
);

