//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// 原始文件名:
// 生成日期: 2010-8-31 19:33:14
namespace DbOperator
{
    
    /// <summary>
    /// 架构中不存在 PASS9 的注释。
    /// </summary>
    public partial class PASS9 : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// 请使用应用程序配置文件的“PASS9”部分中的连接字符串初始化新 PASS9 对象。
        /// </summary>
        public PASS9() : 
                base("name=PASS9", "PASS9")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// 初始化新的 PASS9 对象。
        /// </summary>
        public PASS9(string connectionString) : 
                base(connectionString, "PASS9")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// 初始化新的 PASS9 对象。
        /// </summary>
        public PASS9(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "PASS9")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// 架构中不存在 Tbl_Account 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Tbl_Account> Tbl_Account
        {
            get
            {
                if ((this._Tbl_Account == null))
                {
                    this._Tbl_Account = base.CreateQuery<Tbl_Account>("[Tbl_Account]");
                }
                return this._Tbl_Account;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Tbl_Account> _Tbl_Account;
        /// <summary>
        /// 架构中不存在 Tbl_Record 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Tbl_Record> Tbl_Record
        {
            get
            {
                if ((this._Tbl_Record == null))
                {
                    this._Tbl_Record = base.CreateQuery<Tbl_Record>("[Tbl_Record]");
                }
                return this._Tbl_Record;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Tbl_Record> _Tbl_Record;
        /// <summary>
        /// 架构中不存在 Tbl_Account 的注释。
        /// </summary>
        public void AddToTbl_Account(Tbl_Account tbl_Account)
        {
            base.AddObject("Tbl_Account", tbl_Account);
        }
        /// <summary>
        /// 架构中不存在 Tbl_Record 的注释。
        /// </summary>
        public void AddToTbl_Record(Tbl_Record tbl_Record)
        {
            base.AddObject("Tbl_Record", tbl_Record);
        }
    }
    /// <summary>
    /// 架构中不存在 PASS9Model.Tbl_Account 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PASS9Model", Name="Tbl_Account")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Tbl_Account : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 Tbl_Account 对象。
        /// </summary>
        /// <param name="id">Id 的初始值。</param>
        /// <param name="name">Name 的初始值。</param>
        /// <param name="zoneId">ZoneId 的初始值。</param>
        /// <param name="activeCode">ActiveCode 的初始值。</param>
        public static Tbl_Account CreateTbl_Account(int id, string name, int zoneId, string activeCode)
        {
            Tbl_Account tbl_Account = new Tbl_Account();
            tbl_Account.Id = id;
            tbl_Account.Name = name;
            tbl_Account.ZoneId = zoneId;
            tbl_Account.ActiveCode = activeCode;
            return tbl_Account;
        }
        /// <summary>
        /// 架构中不存在属性 Id 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// 架构中不存在属性 Name 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// 架构中不存在属性 ZoneId 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ZoneId
        {
            get
            {
                return this._ZoneId;
            }
            set
            {
                this.OnZoneIdChanging(value);
                this.ReportPropertyChanging("ZoneId");
                this._ZoneId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ZoneId");
                this.OnZoneIdChanged();
            }
        }
        private int _ZoneId;
        partial void OnZoneIdChanging(int value);
        partial void OnZoneIdChanged();
        /// <summary>
        /// 架构中不存在属性 ActiveCode 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ActiveCode
        {
            get
            {
                return this._ActiveCode;
            }
            set
            {
                this.OnActiveCodeChanging(value);
                this.ReportPropertyChanging("ActiveCode");
                this._ActiveCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ActiveCode");
                this.OnActiveCodeChanged();
            }
        }
        private string _ActiveCode;
        partial void OnActiveCodeChanging(string value);
        partial void OnActiveCodeChanged();
    }
    /// <summary>
    /// 架构中不存在 PASS9Model.Tbl_Record 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PASS9Model", Name="Tbl_Record")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Tbl_Record : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 Tbl_Record 对象。
        /// </summary>
        /// <param name="id">Id 的初始值。</param>
        public static Tbl_Record CreateTbl_Record(int id)
        {
            Tbl_Record tbl_Record = new Tbl_Record();
            tbl_Record.Id = id;
            return tbl_Record;
        }
        /// <summary>
        /// 架构中不存在属性 Id 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
    }
}
