CREATE FUNCTION [dbo].[Fn_GetDateDesc]
(@Date DATETIME)
RETURNS VARCHAR (256)
AS
BEGIN
	DECLARE @RET VARCHAR(256)
	SET @RET = '<t c=''0xffff22ff''>' +CAST(YEAR(@Date) AS VARCHAR(4)) + '年' +
			CAST(MONTH(@Date) AS VARCHAR(2)) + '月' +
			CAST(DAY(@Date) AS VARCHAR(2)) + '日</t>'
	RETURN @RET
END