/*CREATE NONCLUSTERED INDEX [IDX_TBL_Player_Deleted_PlayerName]
    ON [dbo].[Tbl_Player_Deleted]([PlayerName] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0);*/

