CREATE NONCLUSTERED INDEX [IX_Tbl_Dinner_Player]
    ON [dbo].[Tbl_Dinner]([PlayerID0] ASC, [PlayerID1] ASC, [PlayerID2] ASC, [PlayerID3] ASC, [PlayerID4] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0);

