ALTER TABLE [dbo].[Tbl_MailList_Deleted]
    ADD CONSTRAINT [PK_Tbl_MailList_Deleted] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

