ALTER TABLE [dbo].[Tbl_Officer]
    ADD CONSTRAINT [PK_Tbl_Officer] PRIMARY KEY CLUSTERED ([OfficerID] ASC, [PlayerID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

