ALTER TABLE [dbo].[Tbl_LogPlayer]
    ADD CONSTRAINT [PK_Tbl_LogPlayer] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

