ALTER TABLE [dbo].[Tbl_Skill]
    ADD CONSTRAINT [PK_Tbl_Skill] PRIMARY KEY CLUSTERED ([Series] ASC, [PlayerID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

