ALTER TABLE [dbo].[Tbl_City]
    ADD CONSTRAINT [PK_Tbl_City] PRIMARY KEY CLUSTERED ([CityID] ASC, [PlayerID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

