ALTER TABLE [dbo].[Tbl_Dinner_Delete]
    ADD CONSTRAINT [PK_Tbl_Dinner_Delete] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);
