ALTER TABLE [dbo].[Tbl_Player_Deleted]
    ADD CONSTRAINT [PK_Tbl_Player_Deleted] PRIMARY KEY CLUSTERED ([PlayerID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

