ALTER TABLE [dbo].[Tbl_OrgMember]
    ADD CONSTRAINT [PK_Tbl_OrgMember] PRIMARY KEY CLUSTERED ([PlayerId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

