ALTER TABLE [dbo].[Tbl_TimeSet]
    ADD CONSTRAINT [PK_Tbl_TimeSet] PRIMARY KEY CLUSTERED ([ID] ASC, [PlayerID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

