/*ALTER TABLE [dbo].[Tbl_Social]
    ADD CONSTRAINT [PK_Tbl_Social_1] PRIMARY KEY CLUSTERED ([player] ASC, [target] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

