ALTER TABLE [dbo].[Tbl_OrgSkill]
    ADD CONSTRAINT [PK_Tbl_OrgSkill] PRIMARY KEY CLUSTERED ([SkillId] ASC, [OrgId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

