ALTER TABLE [dbo].[Tbl_Battle]
    ADD CONSTRAINT [PK_Tbl_Battle] PRIMARY KEY CLUSTERED ([PlayerID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

