ALTER TABLE [dbo].[Tbl_Item]
    ADD CONSTRAINT [PK_Tbl_Item] PRIMARY KEY CLUSTERED ([UID] ASC, [PlayerID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

