ALTER TABLE [dbo].[Tbl_Equip]
    ADD CONSTRAINT [PK_Tbl_Equip] PRIMARY KEY CLUSTERED ([UID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

