/*ALTER TABLE [dbo].[Tbl_Achievement_Info]
    ADD CONSTRAINT [PK_Tbl_Achievement_Info] PRIMARY KEY CLUSTERED ([PlayerID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

