/*ALTER TABLE [dbo].[Tbl_MissionFlag]
    ADD CONSTRAINT [PK_Tbl_MissionFlag] PRIMARY KEY CLUSTERED ([PlayerID] ASC, [MissionID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

