/*ALTER TABLE [dbo].[Tbl_InventoryItem]
    ADD CONSTRAINT [PK_Tbl_InventoryItem_1] PRIMARY KEY CLUSTERED ([PlayerID] ASC, [ItemPos] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

