/*ALTER TABLE [dbo].[Tbl_Panel]
    ADD CONSTRAINT [PK_Tbl_Panel] PRIMARY KEY CLUSTERED ([PlayerID] ASC, [Pos] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

