/*ALTER TABLE [dbo].[Tbl_TimeSet]
    ADD CONSTRAINT [PK_Tbl_TimeSet] PRIMARY KEY CLUSTERED ([PlayerID] ASC, [id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

