/*ALTER TABLE [dbo].[Tbl_Spirit]
    ADD CONSTRAINT [PK_TBL_Spirit] PRIMARY KEY CLUSTERED ([PlayerID] ASC, [Pos] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

