/*ALTER TABLE [dbo].[Tbl_Prescription]
    ADD CONSTRAINT [PK_Tbl_Prescription] PRIMARY KEY CLUSTERED ([PlayerID] ASC, [ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

