CREATE TABLE [dbo].[Tbl_ActivityDel] (
    [ID]			INT			NOT NULL,
    [Type]			INT			CONSTRAINT [DF_Tbl_ActivityDel_Type]			DEFAULT((0))				NOT NULL,
	[Name]			VARCHAR(32) CONSTRAINT [DF_Tbl_ActivityDel_Name]			DEFAULT((''))				NOT NULL,
	[Contend]		VARCHAR(256)CONSTRAINT [DF_Tbl_ActivityDel_Contend]			DEFAULT((''))				NOT NULL,
	[BeginTime]		DATETIME	CONSTRAINT [DF_Tbl_ActivityDel_BeginTime]		DEFAULT((getdate()))		NOT NULL,
	[EndTime]		DATETIME	CONSTRAINT [DF_Tbl_ActivityDel_EndTime]			DEFAULT((getdate()))		NOT NULL,
	[ItemId0]		INT			CONSTRAINT [DF_Tbl_ActivityDel_ItemId0]			DEFAULT((0))				NOT NULL,
	[ItemId1]		INT			CONSTRAINT [DF_Tbl_ActivityDel_ItemId1]			DEFAULT((0))				NOT NULL,
	[ItemId2]		INT			CONSTRAINT [DF_Tbl_ActivityDel_ItemId2]			DEFAULT((0))				NOT NULL,
	[ItemId3]		INT			CONSTRAINT [DF_Tbl_ActivityDel_ItemId3]			DEFAULT((0))				NOT NULL,
	[ItemNum0]		INT			CONSTRAINT [DF_Tbl_ActivityDel_ItemNum0]		DEFAULT((0))				NOT NULL,
	[ItemNum1]		INT			CONSTRAINT [DF_Tbl_ActivityDel_ItemNum1]		DEFAULT((0))				NOT NULL,
	[ItemNum2]		INT			CONSTRAINT [DF_Tbl_ActivityDel_ItemNum2]		DEFAULT((0))				NOT NULL,
	[ItemNum3]		INT			CONSTRAINT [DF_Tbl_ActivityDel_ItemNum3]		DEFAULT((0))				NOT NULL,
	[Extend0]		INT			CONSTRAINT [DF_Tbl_ActivityDel_Extend0]			DEFAULT((0))				NOT NULL,
	[Extend1]		INT			CONSTRAINT [DF_Tbl_ActivityDel_Extend1]			DEFAULT((0))				NOT NULL,
	[Extend2]		INT			CONSTRAINT [DF_Tbl_ActivityDel_Extend2]			DEFAULT((0))				NOT NULL,
	[Extend3]		INT			CONSTRAINT [DF_Tbl_ActivityDel_Extend3]			DEFAULT((0))				NOT NULL,
	[CreateTime]	DATETIME	CONSTRAINT [DF_Tbl_ActivityDel_CreateTime]		DEFAULT((getdate()))		NOT NULL,
);