CREATE TABLE [dbo].[Tbl_Org] (
    [Id]			INT																			NOT NULL,
    [Level]			INT			CONSTRAINT	[DF_Tbl_OrgLevel]				DEFAULT((0))		NOT NULL,
    [Exp]			INT	   		CONSTRAINT	[DF_Tbl_OrgExp]					DEFAULT((0))		NOT NULL,
    [SkillPoint]    INT			CONSTRAINT	[DF_Tbl_OrgSkillPoint]			DEFAULT((0))		NOT NULL,
	[Name]			VARCHAR(32)	CONSTRAINT	[DF_Tbl_OrgName]				DEFAULT((''))		NOT NULL,
	[Qq]			VARCHAR(180)CONSTRAINT	[DF_Tbl_OrgQq]					DEFAULT((''))		NOT NULL,
	[Msg]			VARCHAR(180)CONSTRAINT	[DF_Tbl_OrgMsg]					DEFAULT((''))		NOT NULL,
	[Memo]			VARCHAR(180)CONSTRAINT	[DF_Tbl_OrgMemo]				DEFAULT((''))		NOT NULL,
	[MasterId]		INT			CONSTRAINT	[DF_Tbl_OrgMasterId]			DEFAULT((0))		NOT NULL,
	[TransferTime]	DATETIME	CONSTRAINT	[DF_Tbl_OrgTransferTime]		DEFAULT((getdate()))NOT NULL,
	[BattleVal]		INT			CONSTRAINT	[DF_Tbl_OrgBattleVal]			DEFAULT((0))		NOT NULL,
	[PlayerNum]		SMALLINT	CONSTRAINT	[DF_Tbl_OrgPlayerNum]			DEFAULT((0))		NOT NULL,
	[MaxPlayerNum]	SMALLINT	CONSTRAINT	[DF_Tbl_OrgMaxPlayerNum]		DEFAULT((10))		NOT NULL,
	[MaxEliteNum]	SMALLINT	CONSTRAINT	[DF_Tbl_OrgMaxElitePlayerNum]	DEFAULT((0))		NOT NULL,
	[AutoAcceptJoin]TINYINT		CONSTRAINT	[DF_Tbl_OrgAutoAcceptJoin]		DEFAULT((0))		NOT NULL,
	[OrgBossTimes]	TINYINT		CONSTRAINT  [DF_Tbl_OrgBossTimes]			DEFAULT((0))		NOT NULL,
	[OrgBossTime]	DATETIME	CONSTRAINT	[DF_Tbl_OrgBossTime]			DEFAULT((getdate()))NOT NULL,
);