CREATE TABLE [dbo].[Tbl_Dinner] (
	[Id]				 INT			IDENTITY (1, 1) NOT NULL,
	[DinnerState]		 INT			CONSTRAINT		[DF_Tbl_Dinner_DinnerState] DEFAULT(0)	NOT NULL,
	[DinnerNum]			 INT			CONSTRAINT		[DF_Tbl_Dinner_DinnerNum]	DEFAULT(0)	NOT NULL,
	[DinnerType]		 INT			CONSTRAINT		[DF_Tbl_Dinner_DinnerType]	DEFAULT(0)	NOT NULL,
	[CreateTime]		 INT			CONSTRAINT		[DF_Tbl_Dinner_CreateTime]	DEFAULT(0)	NOT NULL,

    [PlayerID0]			 INT			CONSTRAINT		[DF_Tbl_Dinner_PlayerID0]	DEFAULT(0)	NOT NULL,
	[PlayerID1]			 INT			CONSTRAINT		[DF_Tbl_Dinner_PlayerID1]	DEFAULT(0)	NOT NULL,
	[PlayerID2]			 INT			CONSTRAINT		[DF_Tbl_Dinner_PlayerID2]	DEFAULT(0)	NOT NULL,
	[PlayerID3]			 INT			CONSTRAINT		[DF_Tbl_Dinner_PlayerID3]	DEFAULT(0)	NOT NULL,
	[PlayerID4]			 INT			CONSTRAINT		[DF_Tbl_Dinner_PlayerID4]	DEFAULT(0)	NOT NULL,

	[PlayerName0]		 VARCHAR(32)	CONSTRAINT		[DF_Tbl_Dinner_PlayerName0]	DEFAULT(0)	NOT NULL,
	[PlayerName1]		 VARCHAR(32)	CONSTRAINT		[DF_Tbl_Dinner_PlayerName1]	DEFAULT(0)	NOT NULL,
	[PlayerName2]		 VARCHAR(32)	CONSTRAINT		[DF_Tbl_Dinner_PlayerName2]	DEFAULT(0)	NOT NULL,
	[PlayerName3]		 VARCHAR(32)	CONSTRAINT		[DF_Tbl_Dinner_PlayerName3]	DEFAULT(0)	NOT NULL,
	[PlayerName4]		 VARCHAR(32)	CONSTRAINT		[DF_Tbl_Dinner_PlayerName4]	DEFAULT(0)	NOT NULL,

	[JoinType0]			 TINYINT		CONSTRAINT		[DF_Tbl_Dinner_JoinType0]	DEFAULT(0)	NOT NULL,
	[JoinType1]			 TINYINT		CONSTRAINT		[DF_Tbl_Dinner_JoinType1]	DEFAULT(0)	NOT NULL,
	[JoinType2]			 TINYINT		CONSTRAINT		[DF_Tbl_Dinner_JoinType2]	DEFAULT(0)	NOT NULL,
	[JoinType3]			 TINYINT		CONSTRAINT		[DF_Tbl_Dinner_JoinType3]	DEFAULT(0)	NOT NULL,
	[JoinType4]			 TINYINT		CONSTRAINT		[DF_Tbl_Dinner_JoinType4]	DEFAULT(0)	NOT NULL,

	[PrincessID0]		 INT			CONSTRAINT		[DF_Tbl_Dinner_PrincessID0]	DEFAULT(0)	NOT NULL,
	[PrincessID1]		 INT			CONSTRAINT		[DF_Tbl_Dinner_PrincessID1]	DEFAULT(0)	NOT NULL,
	[PrincessID2]		 INT			CONSTRAINT		[DF_Tbl_Dinner_PrincessID2]	DEFAULT(0)	NOT NULL,
	[PrincessID3]		 INT			CONSTRAINT		[DF_Tbl_Dinner_PrincessID3]	DEFAULT(0)	NOT NULL,
	[PrincessID4]		 INT			CONSTRAINT		[DF_Tbl_Dinner_PrincessID4]	DEFAULT(0)	NOT NULL,

	[PrincessSkill0]	 VARCHAR(32)	CONSTRAINT		[DF_Tbl_Dinner_PrincessSkill0]DEFAULT('AAAAAAAAAAAAAAAAAAAAAA==')	NOT NULL,
	[PrincessSkill1]	 VARCHAR(32)	CONSTRAINT		[DF_Tbl_Dinner_PrincessSkill1]DEFAULT('AAAAAAAAAAAAAAAAAAAAAA==')	NOT NULL,
	[PrincessSkill2]	 VARCHAR(32)	CONSTRAINT		[DF_Tbl_Dinner_PrincessSkill2]DEFAULT('AAAAAAAAAAAAAAAAAAAAAA==')	NOT NULL,
	[PrincessSkill3]	 VARCHAR(32)	CONSTRAINT		[DF_Tbl_Dinner_PrincessSkill3]DEFAULT('AAAAAAAAAAAAAAAAAAAAAA==')	NOT NULL,
	[PrincessSkill4]	 VARCHAR(32)	CONSTRAINT		[DF_Tbl_Dinner_PrincessSkill4]DEFAULT('AAAAAAAAAAAAAAAAAAAAAA==')	NOT NULL,

	[ScoreData0]			VARCHAR(120)		CONSTRAINT		[DF_Tbl_Dinner_ScoreData0]		DEFAULT('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')	NOT NULL,
	[ScoreData1]			VARCHAR(120)		CONSTRAINT		[DF_Tbl_Dinner_ScoreData1]		DEFAULT('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')	NOT NULL,
	[ScoreData2]			VARCHAR(120)		CONSTRAINT		[DF_Tbl_Dinner_ScoreData2]		DEFAULT('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')	NOT NULL,
	[ScoreData3]			VARCHAR(120)		CONSTRAINT		[DF_Tbl_Dinner_ScoreData3]		DEFAULT('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')	NOT NULL,
	[ScoreData4]			VARCHAR(120)		CONSTRAINT		[DF_Tbl_Dinner_ScoreData4]		DEFAULT('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')	NOT NULL,

	[InfoData0]				VARCHAR(32)			CONSTRAINT		[DF_Tbl_Dinner_InfoData0]		DEFAULT('AAAAAAAAAAAAAAAAAAAAAA==')	NOT NULL,
	[InfoData1]				VARCHAR(32)			CONSTRAINT		[DF_Tbl_Dinner_InfoData1]		DEFAULT('AAAAAAAAAAAAAAAAAAAAAA==')	NOT NULL,
	[InfoData2]				VARCHAR(32)			CONSTRAINT		[DF_Tbl_Dinner_InfoData2]		DEFAULT('AAAAAAAAAAAAAAAAAAAAAA==')	NOT NULL,
	[InfoData3]				VARCHAR(32)			CONSTRAINT		[DF_Tbl_Dinner_InfoData3]		DEFAULT('AAAAAAAAAAAAAAAAAAAAAA==')	NOT NULL,
	[InfoData4] 			VARCHAR(32)			CONSTRAINT		[DF_Tbl_Dinner_InfoData4]		DEFAULT('AAAAAAAAAAAAAAAAAAAAAA==')	NOT NULL,
);