CREATE TABLE [dbo].[Tbl_Dinner_Delete] (
	[Id]				 INT			NOT NULL,
	[DinnerState]		 INT			CONSTRAINT		[DF_Tbl_Dinner_Delete_DinnerState] DEFAULT(0)	NOT NULL,
	[DinnerNum]			 INT			CONSTRAINT		[DF_Tbl_Dinner_Delete_DinnerNum]	DEFAULT(0)	NOT NULL,
	[DinnerType]		 INT			CONSTRAINT		[DF_Tbl_Dinner_Delete_DinnerType]	DEFAULT(0)	NOT NULL,
	[CreateTime]		 INT			CONSTRAINT		[DF_Tbl_Dinner_Delete_CreateTime]	DEFAULT(0)	NOT NULL,

    [PlayerID0]			 INT			CONSTRAINT		[DF_Tbl_Dinner_Delete_PlayerID0]	DEFAULT(0)	NOT NULL,
	[PlayerID1]			 INT			CONSTRAINT		[DF_Tbl_Dinner_Delete_PlayerID1]	DEFAULT(0)	NOT NULL,
	[PlayerID2]			 INT			CONSTRAINT		[DF_Tbl_Dinner_Delete_PlayerID2]	DEFAULT(0)	NOT NULL,
	[PlayerID3]			 INT			CONSTRAINT		[DF_Tbl_Dinner_Delete_PlayerID3]	DEFAULT(0)	NOT NULL,
	[PlayerID4]			 INT			CONSTRAINT		[DF_Tbl_Dinner_Delete_PlayerID4]	DEFAULT(0)	NOT NULL,

	[PlayerName0]		 VARCHAR(32)	CONSTRAINT		[DF_Tbl_Dinner_Delete_PlayerName0]	DEFAULT(0)	NOT NULL,
	[PlayerName1]		 VARCHAR(32)	CONSTRAINT		[DF_Tbl_Dinner_Delete_PlayerName1]	DEFAULT(0)	NOT NULL,
	[PlayerName2]		 VARCHAR(32)	CONSTRAINT		[DF_Tbl_Dinner_Delete_PlayerName2]	DEFAULT(0)	NOT NULL,
	[PlayerName3]		 VARCHAR(32)	CONSTRAINT		[DF_Tbl_Dinner_Delete_PlayerName3]	DEFAULT(0)	NOT NULL,
	[PlayerName4]		 VARCHAR(32)	CONSTRAINT		[DF_Tbl_Dinner_Delete_PlayerName4]	DEFAULT(0)	NOT NULL,

	[JoinType0]			 TINYINT		CONSTRAINT		[DF_Tbl_Dinner_Delete_JoinType0]	DEFAULT(0)	NOT NULL,
	[JoinType1]			 TINYINT		CONSTRAINT		[DF_Tbl_Dinner_Delete_JoinType1]	DEFAULT(0)	NOT NULL,
	[JoinType2]			 TINYINT		CONSTRAINT		[DF_Tbl_Dinner_Delete_JoinType2]	DEFAULT(0)	NOT NULL,
	[JoinType3]			 TINYINT		CONSTRAINT		[DF_Tbl_Dinner_Delete_JoinType3]	DEFAULT(0)	NOT NULL,
	[JoinType4]			 TINYINT		CONSTRAINT		[DF_Tbl_Dinner_Delete_JoinType4]	DEFAULT(0)	NOT NULL,

	[PrincessID0]		 INT			CONSTRAINT		[DF_Tbl_Dinner_Delete_PrincessID0]	DEFAULT(0)	NOT NULL,
	[PrincessID1]		 INT			CONSTRAINT		[DF_Tbl_Dinner_Delete_PrincessID1]	DEFAULT(0)	NOT NULL,
	[PrincessID2]		 INT			CONSTRAINT		[DF_Tbl_Dinner_Delete_PrincessID2]	DEFAULT(0)	NOT NULL,
	[PrincessID3]		 INT			CONSTRAINT		[DF_Tbl_Dinner_Delete_PrincessID3]	DEFAULT(0)	NOT NULL,
	[PrincessID4]		 INT			CONSTRAINT		[DF_Tbl_Dinner_Delete_PrincessID4]	DEFAULT(0)	NOT NULL,

	[PrincessSkill0]	 VARCHAR(32)	CONSTRAINT		[DF_Tbl_Dinner_Delete_PrincessSkill0]DEFAULT('AAAAAAAAAAAAAAAAAAAAAA==')	NOT NULL,
	[PrincessSkill1]	 VARCHAR(32)	CONSTRAINT		[DF_Tbl_Dinner_Delete_PrincessSkill1]DEFAULT('AAAAAAAAAAAAAAAAAAAAAA==')    NOT NULL,
	[PrincessSkill2]	 VARCHAR(32)	CONSTRAINT		[DF_Tbl_Dinner_Delete_PrincessSkill2]DEFAULT('AAAAAAAAAAAAAAAAAAAAAA==')	NOT NULL,
	[PrincessSkill3]	 VARCHAR(32)	CONSTRAINT		[DF_Tbl_Dinner_Delete_PrincessSkill3]DEFAULT('AAAAAAAAAAAAAAAAAAAAAA==')	NOT NULL,
	[PrincessSkill4]	 VARCHAR(32)	CONSTRAINT		[DF_Tbl_Dinner_Delete_PrincessSkill4]DEFAULT('AAAAAAAAAAAAAAAAAAAAAA==')	NOT NULL,

	[ScoreData0]			VARCHAR(120)		CONSTRAINT		[DF_Tbl_Dinner_Delete_ScoreData0]		DEFAULT('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')	NOT NULL,
	[ScoreData1]			VARCHAR(120)		CONSTRAINT		[DF_Tbl_Dinner_Delete_ScoreData1]		DEFAULT('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')	NOT NULL,
	[ScoreData2]			VARCHAR(120)		CONSTRAINT		[DF_Tbl_Dinner_Delete_ScoreData2]		DEFAULT('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')	NOT NULL,
	[ScoreData3]			VARCHAR(120)		CONSTRAINT		[DF_Tbl_Dinner_Delete_ScoreData3]		DEFAULT('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')	NOT NULL,
	[ScoreData4]			VARCHAR(120)		CONSTRAINT		[DF_Tbl_Dinner_Delete_ScoreData4]		DEFAULT('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')	NOT NULL,

	[InfoData0]				VARCHAR(32)			CONSTRAINT		[DF_Tbl_Dinner_Delete_InfoData0]		DEFAULT('AAAAAAAAAAAAAAAAAAAAAA==')	NOT NULL,
	[InfoData1]				VARCHAR(32)			CONSTRAINT		[DF_Tbl_Dinner_Delete_InfoData1]		DEFAULT('AAAAAAAAAAAAAAAAAAAAAA==')	NOT NULL,
	[InfoData2]				VARCHAR(32)			CONSTRAINT		[DF_Tbl_Dinner_Delete_InfoData2]		DEFAULT('AAAAAAAAAAAAAAAAAAAAAA==')	NOT NULL,
	[InfoData3]				VARCHAR(32)			CONSTRAINT		[DF_Tbl_Dinner_Delete_InfoData3]		DEFAULT('AAAAAAAAAAAAAAAAAAAAAA==')	NOT NULL,
	[InfoData4] 			VARCHAR(32)			CONSTRAINT		[DF_Tbl_Dinner_Delete_InfoData4]		DEFAULT('AAAAAAAAAAAAAAAAAAAAAA==')	NOT NULL,

	[deletetime]		DATETIME			CONSTRAINT		[DF_Delete_deletetime]	DEFAULT((getdate()))			NOT NULL
);