CREATE TABLE [dbo].[Tbl_Activity] (
    [ID]			INT			IDENTITY(1,1)			NOT NULL,
    [Type]			INT			CONSTRAINT [DF_Tbl_Activity_Type]			DEFAULT((0))				NOT NULL,
	[Name]			VARCHAR(32) CONSTRAINT [DF_Tbl_Activity_Name]			DEFAULT((''))				NOT NULL,
	[Contend]		VARCHAR(256)CONSTRAINT [DF_Tbl_Activity_Contend]		DEFAULT((''))				NOT NULL,
	[BeginTime]		DATETIME	CONSTRAINT [DF_Tbl_Activity_BeginTime]		DEFAULT((getdate()))		NOT NULL,
	[EndTime]		DATETIME	CONSTRAINT [DF_Tbl_Activity_EndTime]		DEFAULT((getdate()))		NOT NULL,
	[ItemId0]		INT			CONSTRAINT [DF_Tbl_Activity_ItemId0]		DEFAULT((0))				NOT NULL,
	[ItemId1]		INT			CONSTRAINT [DF_Tbl_Activity_ItemId1]		DEFAULT((0))				NOT NULL,
	[ItemId2]		INT			CONSTRAINT [DF_Tbl_Activity_ItemId2]		DEFAULT((0))				NOT NULL,
	[ItemId3]		INT			CONSTRAINT [DF_Tbl_Activity_ItemId3]		DEFAULT((0))				NOT NULL,
	[ItemNum0]		INT			CONSTRAINT [DF_Tbl_Activity_ItemNum0]		DEFAULT((0))				NOT NULL,
	[ItemNum1]		INT			CONSTRAINT [DF_Tbl_Activity_ItemNum1]		DEFAULT((0))				NOT NULL,
	[ItemNum2]		INT			CONSTRAINT [DF_Tbl_Activity_ItemNum2]		DEFAULT((0))				NOT NULL,
	[ItemNum3]		INT			CONSTRAINT [DF_Tbl_Activity_ItemNum3]		DEFAULT((0))				NOT NULL,
	[Extend0]		INT			CONSTRAINT [DF_Tbl_Activity_Extend0]		DEFAULT((0))				NOT NULL,
	[Extend1]		INT			CONSTRAINT [DF_Tbl_Activity_Extend1]		DEFAULT((0))				NOT NULL,
	[Extend2]		INT			CONSTRAINT [DF_Tbl_Activity_Extend2]		DEFAULT((0))				NOT NULL,
	[Extend3]		INT			CONSTRAINT [DF_Tbl_Activity_Extend3]		DEFAULT((0))				NOT NULL,
	[CreateTime]	DATETIME	CONSTRAINT [DF_Tbl_Activity_CreateTime]		DEFAULT((getdate()))		NOT NULL,
);