-- =============================================
-- Author:		<Daniel>
-- Create date: <2012-04-16>
-- Description:	<校验IP是否合法>
-- =============================================
CREATE FUNCTION [dbo].[UFN_CHECKIP]
(
	@IP	VARCHAR(20)
)
RETURNS INT
AS
BEGIN
	DECLARE @RET INT
	DECLARE @SEG1 VARCHAR(3), @SEG2 VARCHAR(3),
		@SEG3 VARCHAR(3), @SEG4 VARCHAR(3)
	SET @SEG1 = PARSENAME(@IP,1)
	SET @SEG2 = PARSENAME(@IP,2)
	SET @SEG3 = PARSENAME(@IP,3)
	SET @SEG4 = PARSENAME(@IP,4)
	IF ISNUMERIC(@SEG1) = 1 AND CAST(@SEG1 AS INT) BETWEEN 1 AND 255 AND
		ISNUMERIC(@SEG2) = 1 AND CAST(@SEG2 AS INT) BETWEEN 1 AND 255 AND
		ISNUMERIC(@SEG3) = 1 AND CAST(@SEG3 AS INT) BETWEEN 1 AND 255 AND 
		ISNUMERIC(@SEG4) = 1 AND CAST(@SEG4 AS INT) BETWEEN 1 AND 255
		SET @RET = 1
	ELSE
		SET @RET = 0
	RETURN @RET
END
