ALTER TABLE [dbo].[T_USER_PAY]
    ADD CONSTRAINT [PK_TUSERPAY_ACCOUNT] PRIMARY KEY CLUSTERED ([ACCOUNTID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

