CREATE PROCEDURE [dbo].[Sp_ImportGoods_Item]
@FILEPATH VARCHAR (250), @FIELDTERMINATOR VARCHAR (10)='	'
AS
BEGIN
	DECLARE @SQL VARCHAR(MAX)
	TRUNCATE TABLE Tbl_Goods_Item
	CREATE TABLE # (goodsid int, itemid int, itemnum smallint)
	
	SELECT @SQL = 'BULK INSERT # ' + CHAR(13) +
	'FROM '''+ @FILEPATH + '''' + CHAR(13) +
	'WITH ('+ CHAR(13) +
			'FIELDTERMINATOR ='''+ @FIELDTERMINATOR+''','+CHAR(13)+
			'ROWTERMINATOR =''\n'','+CHAR(13)+
			'TABLOCK' + CHAR(13)+
		')'
	PRINT @SQL
	ALTER DATABASE BILLING SET RECOVERY BULK_LOGGED
	EXEC(@SQL)
	INSERT INTO Tbl_Goods_Item (goodsid, itemid, itemnum) SELECT * FROM #
	ALTER DATABASE BILLING SET RECOVERY FULL
END