ALTER TABLE [dbo].[TBL_SERVER_LIST]
    ADD CONSTRAINT [PK_TBL_SERVER_LIST] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

