ALTER TABLE [dbo].[TBL_CodeHistory]
    ADD CONSTRAINT [PK_TBL_CodeHistory] PRIMARY KEY CLUSTERED ([UID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

