ALTER TABLE [dbo].[TBL_CmdGift]
    ADD CONSTRAINT [PK_TBL_CmdGift] PRIMARY KEY CLUSTERED ([Code] ASC, [PlayerID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

