ALTER TABLE [dbo].[TBL_AUTH]
    ADD CONSTRAINT [PK_TBL_AUTH] PRIMARY KEY CLUSTERED ([ACCOUNT_ID] ASC, [TOKEN] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

