ALTER TABLE [dbo].[TBL_PurhaseConf]
    ADD CONSTRAINT [PK_TBL_PurhaseConf] PRIMARY KEY CLUSTERED ([product_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

