ALTER TABLE [dbo].[TBL_ACCOUNTRENAME]
    ADD CONSTRAINT [PK_TBL_ACCOUNTRENAME_1] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

