ALTER TABLE [dbo].[TBL_PURCHASE]
    ADD CONSTRAINT [PK_TBL_PURCHASE] PRIMARY KEY CLUSTERED ([UID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

