CREATE PROCEDURE [dbo].[USP_QUERYMONTHPAYS_SXZ]
@AccountID INT
AS
BEGIN
	SET NOCOUNT ON
	DECLARE @MonthPays INT, @PayGold INT
	SELECT @MonthPays=COUNT(*) FROM GAME_CHARGE_HISTORY 
		WHERE ACCOUNTID = @AccountID AND PAY_POINTS > 0 AND 
			CREATEDATE >= CONVERT(VARCHAR(10), DATEADD(DD,DAY(GETDATE())*-1+1, GETDATE()),121) AND 
			CREATEDATE < CONVERT(VARCHAR(10), DATEADD(MM,1,DATEADD(DD,DAY(GETDATE())*-1+1,GETDATE())),121)
	SELECT @PayGold=PAY_POINTS FROM T_USER_PAY WHERE AccountID=@AccountID
	IF @@ROWCOUNT = 0
		SET @PayGold = 0
	SELECT @PayGold,@MonthPays
END