CREATE PROCEDURE [dbo].[USP_USERBUYITEM]
	@PURCHASE_TYPE	CHAR(1),		--1,古币消费;2,积分消费
	@ACCOUNTID		INT,
	@PLAYERID		BIGINT,
	@ORDERID		INT,
	@TOTALPRICE		INT,
	@IP				VARCHAR(15),
	@MAC			VARCHAR(20),
	@RESULT CHAR(4) = '0001' OUTPUT

AS
BEGIN

	SET NOCOUNT ON;
	SET XACT_ABORT ON;
	DECLARE @PAY_POINTS INT,@FREE_POINTS INT,@HONOR INT,@ITEMNAME NVARCHAR(100),@ITEMUNIQUE INT,@ITEMPRICE INT,@HONORPRICE INT 
    SELECT @RESULT = '0000',@PAY_POINTS = 0,@FREE_POINTS = 0,@HONOR = 0

	SELECT @PAY_POINTS = PAY_POINTS,@FREE_POINTS = FREE_POINTS,@HONOR = HONOR
	FROM DBO.T_USER_PAY
	WHERE ACCOUNTID = @ACCOUNTID

	IF @RESULT = '0000' 
	BEGIN
		BEGIN TRAN
			
		IF @PURCHASE_TYPE = '1'
		BEGIN
			IF @FREE_POINTS+@PAY_POINTS < @TOTALPRICE
			BEGIN
				SET @RESULT = '0002'
			END

			IF @RESULT = '0000'
			BEGIN
				IF @FREE_POINTS >= @TOTALPRICE
				BEGIN
					UPDATE DBO.T_USER_PAY
					SET FREE_POINTS = @FREE_POINTS - @TOTALPRICE,HONOR = HONOR + @TOTALPRICE/100
					WHERE ACCOUNTID = @ACCOUNTID
					IF @@ERROR <> 0 
					BEGIN
						SET @RESULT = '0004'
					END
					
					IF @RESULT = '0000'
					BEGIN
						INSERT INTO DBO.TBL_USER_PURCHASE_HISTORY(DATE,ACCOUNTID,ORDERID,COST_PAYPOINTS,COST_FREEPOINTS,COST_HONOR,GET_HONOR,LEFT_PAYPOINTS,LEFT_FREEPOINTS,LEFT_HONOR,IP,MAC)
							SELECT GETDATE(),ACCOUNTID,@ORDERID,@PAY_POINTS,@FREE_POINTS,(CASE WHEN @PURCHASE_TYPE = '1' THEN @TOTALPRICE/100 ELSE 0 END),
								(CASE WHEN @PURCHASE_TYPE = '2' THEN @TOTALPRICE ELSE 0 END),PAY_POINTS,FREE_POINTS,HONOR,@IP,@MAC
							FROM DBO.T_USER_PAY
							WHERE ACCOUNTID = @ACCOUNTID

					END
				END
				ELSE 
				BEGIN
					UPDATE DBO.T_USER_PAY
					SET FREE_POINTS = 0,HONOR = HONOR + @TOTALPRICE/100,
						PAY_POINTS =  @PAY_POINTS + @FREE_POINTS - @TOTALPRICE
					WHERE ACCOUNTID = @ACCOUNTID
					IF @@ERROR <> 0 
					BEGIN
						SET @RESULT = '0004'
					END
				END
			END
		END
		ELSE IF @PURCHASE_TYPE = '0'
		BEGIN
			IF @HONOR < @TOTALPRICE
				SET @RESULT = '0002'
			IF @RESULT = '0000'
			BEGIN
				UPDATE DBO.T_USER_PAY
				SET HONOR = HONOR - @TOTALPRICE
				WHERE ACCOUNTID = @ACCOUNTID
				IF @@ERROR <> 0 
					SET @RESULT = '0004'
			END
		END
	IF @RESULT = '0000'
		COMMIT TRAN
	END
	
END
