CREATE PROCEDURE [dbo].[USP_CHECKBALANCE_SXZ]
@MESSAGEIDI INT, @SEQUENCEI BIGINT, @USERID VARCHAR (100), @SITESERVERID VARCHAR (10), @MESSAGEID INT, @SEQUENCE BIGINT, @RESULT CHAR (4) OUTPUT, @REMAINQUANTITY INT OUTPUT, @ENDDATE DATETIME OUTPUT
AS
BEGIN

	SET NOCOUNT ON

	
	SELECT @MESSAGEID = @MESSAGEIDI,@SEQUENCE = @SEQUENCEI,@REMAINQUANTITY = 0,
		@ENDDATE = GETDATE(),@RESULT = '0000'

	IF NOT EXISTS (SELECT 1 FROM SXZ_BILL.DBO.T_USER_PAY WHERE ACCOUNTID = (SELECT ACCOUNTID FROM SXZ_ACCOUNTDB.DBO.TBL_ACCOUNT WHERE ACCOUNT=@USERID))
	BEGIN
		SET @RESULT = '0003'
	END

	IF @RESULT = '0000'
	BEGIN
		SELECT @REMAINQUANTITY = PAY_POINTS + FREE_POINTS,@ENDDATE = GETDATE()+90
		FROM SXZ_BILL.DBO.T_USER_PAY
		WHERE ACCOUNTID = (SELECT ACCOUNTID FROM SXZ_ACCOUNTDB.DBO.TBL_ACCOUNT WHERE ACCOUNT=@USERID)
	END

	RETURN
END
