ALTER TABLE [dbo].[Tbl_Board]
    ADD CONSTRAINT [PK_Tbl_Board] PRIMARY KEY CLUSTERED ([MsgId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

