ALTER TABLE [dbo].[Tbl_TradeGoods]
    ADD CONSTRAINT [PK_Tbl_TradeGood] PRIMARY KEY CLUSTERED ([TradeGoodsID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

