ALTER TABLE [dbo].[Tbl_Goods_Item_OLD]
    ADD CONSTRAINT [PK_Tbl_Goods_Item_OLD] PRIMARY KEY CLUSTERED ([GoodsID] ASC, [ItemID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

