ALTER TABLE [dbo].[Tbl_Discount]
    ADD CONSTRAINT [PK_Tbl_Biling_Discount] PRIMARY KEY CLUSTERED ([DiscountID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

