ALTER TABLE [dbo].[Tbl_Discount_OLD]
    ADD CONSTRAINT [PK_Tbl_Discount_OLD] PRIMARY KEY CLUSTERED ([DiscountID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

