/*ALTER TABLE [dbo].[Tbl_Item]
    ADD CONSTRAINT [PK_Tbl_Billing_Item] PRIMARY KEY CLUSTERED ([ItemID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

