#pragma once

//副本难度
enum RandMapLevel
{
	EM_COPYMAP_DIFFI_BEGIN = 0,
	EM_COPYMAPDIFF_LV1,
	EM_COPYMAPDIFF_LV2,
	EM_COPYMAPDIFF_LV3,
	EM_COPYMAPDIFF_LV4,

	EM_COPYMAP_END
};

enum COPYMAP_ACTOR
{
	COPYMAP_ACTOR_BEGIN = 0,
	COPYMAP_ACTOR_DEFENCE,
	COPYMAP_ACTOR_DOCTOR,
	COPYMAP_ACTOR_ATTACKER,

	COPYMAP_ACTOR_COUNT,
};

enum RandTeamError
{
    RANDTEAM_ERROR_NONE,
    RANDTEAM_ERROR_REJOIN,          //重复加入等待列表
    RANDTEAM_ERROR_NORANDMAP,       //找不到随机地图
    RANDTEAM_ERROR_CHARFULL,        //角色已满
    RANDTEAM_ERROR_NOTCAPTION,      //不是队长
    RANDTEAM_ERROR_MEMBERJOINFAILED,//加入队员失败
	RANDTEAM_ERROR_NOTEAM,			//找不到队伍
	RANDTEAM_ERROR_COOLDOWN,		//随机组队15分钟冷却
	RANDTEAM_ERROR_KICKED,			//随机组队被表决踢出后无法申请
	RANDTEAM_ERROR_VOTE,			//每隔一段时间只能使用一次踢人权利
	RANDTEAM_ERROR_OFFLINE,			//队伍内有队员不在线
    
    RANDTEAM_ERROR_UNKNOWN,     
};

enum RandteamVote
{
	EM_RANDVOTE_AGINST = 0,
	EM_RANDVOTE_AGREE,
	EM_RANDVOTE_DONTKNOW,
};

enum RandConfirmFlag
{
	EM_RANDCONFIRM_NONE = 0,
	EM_RANDCONFIRM_KICK = 1,
	EM_RANDCONFIRM_ENTER ,
	EM_RANDCONFIRM_ROLECONFIRM,
};

#define SELECT_RAND_TEAM 1000   //选择 “随机地图" 这个选项
#define TEAM_MEMBER_MAX 6

//随机组队的三个BUFF编号
#define BUFF_RADNTEAM_KICKED 9        //被表决踢掉后的BUFF
#define BUFF_RANDTEAM_KICK_PLAYER 10  //发起表决踢出的BUFF
#define BUFF_USE_RANDTEAM 11          //进入副本后的随机组队冷却BUfF