CREATE TABLE [dbo].[Tbl_Player] (
    [PlayerID]            INT          NOT NULL,
    [dbVersion]           INT          NOT NULL,
    [AccountID]           INT          NOT NULL,
    [PlayerName]          VARCHAR (32) NOT NULL,
    [Family]              TINYINT      NOT NULL,
    [Sex]                 TINYINT      NOT NULL,
    [Race]                TINYINT      NOT NULL,
    [CreateTime]          VARCHAR (32) NOT NULL,
    [TotalOnlineTime]     INT          NOT NULL,
    [ZoneID]              INT          NOT NULL,
    [TriggerNo]           INT          NOT NULL,
    [LeavePosX]           FLOAT        NOT NULL,
    [LeavePosY]           FLOAT        NOT NULL,
    [LeavePosZ]           FLOAT        NOT NULL,
    [FZoneId]             INT          NOT NULL,
    [FTriggerNo]          INT          NOT NULL,
    [FID]                 INT          NOT NULL,
    [CopyMapInstId]       INT          NOT NULL,
    [FLeavePosX]          FLOAT        NOT NULL,
    [FLeavePosY]          FLOAT        NOT NULL,
    [FLeavePosZ]          FLOAT        NOT NULL,
    [ApplyDeleteTime]     VARCHAR (32) NOT NULL,
    [FlyPath]             INT          NOT NULL,
    [FlyPos]              INT          NOT NULL,
    [FlyMount]            INT          NOT NULL,
    [SafeTime]            INT          NOT NULL,
    [NewSafeTime]         INT          NOT NULL,
    [NewSafeTimeDate]     VARCHAR (32) NOT NULL,
    [CurrentVir]          INT          NOT NULL,
    [MaxVir]              INT          NOT NULL,
    [CurrentExp]          BIGINT       NOT NULL,
    [CurrentLivingExp]    INT          NOT NULL,
    [ExpPool]             INT          NOT NULL,
    [PKValue]             INT          NOT NULL,
    [TempPKStateTime]     INT          NOT NULL,
    [Level]               SMALLINT     NOT NULL,
    [Classes0]            TINYINT      NOT NULL,
    [Classes1]            TINYINT      NOT NULL,
    [Classes2]            TINYINT      NOT NULL,
    [Classes3]            TINYINT      NOT NULL,
    [Classes4]            TINYINT      NOT NULL,
    [PlayerFunction]      INT          NOT NULL,
    [Honour]              INT          NOT NULL,
    [OtherFlag]           INT          NOT NULL,
    [MasterLevel]         SMALLINT     NOT NULL,
    [CurrMasterExp]       INT          NOT NULL,
    [IsPrentice]          TINYINT      NOT NULL,
    [MPMStudyLevel]       INT          NOT NULL,
    [MasterID]            INT          NOT NULL,
    [LivingLevel]         INT          NOT NULL,
    [PlayerHot]           INT          NOT NULL,
    [Money]               INT          NOT NULL,
    [BindMoney]           INT          NOT NULL,
    [BankMoney]           INT          NOT NULL,
    [BindGold]            INT          NOT NULL,
    [SecondPassword]      VARCHAR (32) NOT NULL,
    [SecondPasswordState] TINYINT      NOT NULL,
    [SecondPWDLeftTime]   INT          NOT NULL,
    [BankBagSize]         INT          NOT NULL,
    [LivingSkillStudyID]  INT          NOT NULL,
    [CurDesignationID]    SMALLINT     NOT NULL,
    [SwitchState]         INT          NOT NULL,
    [MarriageTime]        VARCHAR (32) NOT NULL,
    [LockDivorceTime]     VARCHAR (32) NOT NULL,
    [SueDivorce]          VARCHAR (32) NOT NULL,
    [PetOpenFlag]         SMALLINT     NOT NULL,
    [SpiritOpenedFlag]    SMALLINT     NOT NULL,
    [SpiritActiveSlot]    SMALLINT     NOT NULL,
    [MoHunActiveNum]	  INT      NOT NULL,
    [CurrentGodShipExp]   BIGINT       NOT NULL,
    [HighestBattleVal]    INT          NOT NULL,
    [GodShipLevel]        SMALLINT     NOT NULL,
    [PlayerTransformPet_Pc] SMALLINT   NOT NULL,
);