CREATE TABLE [dbo].[Tbl_Pet] (
    [PlayerID]         INT          NOT NULL,
    [Pos]              TINYINT      NOT NULL,
    [PetUID]           BIGINT       NOT NULL,
    [PetDataID]        INT          NOT NULL,
    [PetName]          VARCHAR (32) NOT NULL,
    [PetEggID]         INT          NOT NULL,
    [PartnerID]        BIGINT       NOT NULL,
    [Sex]              TINYINT      NOT NULL,
    [Style]            TINYINT      NOT NULL,
    [Mature]           TINYINT      NOT NULL,
    [Status]           TINYINT      NOT NULL,
    [Generation]       TINYINT      NOT NULL,
    [Title]            BIGINT       NOT NULL,
    [TitleEnabled]     SMALLINT     NOT NULL,
    [Level]            INT          NOT NULL,
    [Livers]           INT          NOT NULL,
    [CurHP]            INT          NOT NULL,
    [CurMP]            INT          NOT NULL,
    [CurPP]            INT          NOT NULL,
    [StaminaPts]       INT          NOT NULL,
    [ManaPts]          INT          NOT NULL,
    [StrengthPts]      INT          NOT NULL,
    [IntellectPts]     INT          NOT NULL,
    [AgilityPts]       INT          NOT NULL,
    [PneumaPts]        INT          NOT NULL,
    [StatsPoints]      INT          NOT NULL,
    [Insight]          SMALLINT     NOT NULL,
    [PetTalent]        SMALLINT     NOT NULL,
    [IsIdentify]       TINYINT      NOT NULL,
    [ChengZhangLv]     INT          NOT NULL,
    [QianLi]           INT          NOT NULL,
    [Quality]          INT          NOT NULL,
    [StaminaGift]      INT          NOT NULL,
    [ManaGift]         INT          NOT NULL,
    [StrengthGift]     INT          NOT NULL,
    [IntellectGift]    INT          NOT NULL,
    [AgilityGift]      INT          NOT NULL,
    [PneumaGift]       INT          NOT NULL,
    [Happiness]        SMALLINT     NOT NULL,
    [Exp]              INT          NOT NULL,
    [CharPoints]       INT          NOT NULL,
    [LastBreedLv]      SMALLINT     NOT NULL,
    [BabyPetDataID]    INT          NOT NULL,
    [BreedStartTime]   INT          NOT NULL,
    [Combat0]          INT          NOT NULL,
    [Combat1]          INT          NOT NULL,
    [Combat2]          INT          NOT NULL,
    [Combat3]          INT          NOT NULL,
    [Combat4]          INT          NOT NULL,
    [Combat5]          INT          NOT NULL,
    [Combat6]          INT          NOT NULL,
    [Combat7]          INT          NOT NULL,
    [Combat8]          INT          NOT NULL,
    [Combat9]          INT          NOT NULL,
    [Combat10]         INT          NOT NULL,
    [Combat11]         INT          NOT NULL,
    [Combo0]           INT          NOT NULL,
    [Combo1]           INT          NOT NULL,
    [Combo2]           INT          NOT NULL,
    [Combo3]           INT          NOT NULL,
    [Combo4]           INT          NOT NULL,
    [Combo5]           INT          NOT NULL,
    [Combo6]           INT          NOT NULL,
    [Combo7]           INT          NOT NULL,
    [Combo8]           INT          NOT NULL,
    [Combo9]           INT          NOT NULL,
    [Combo10]          INT          NOT NULL,
    [Combo11]          INT          NOT NULL,
    [activeSkillSlot0] SMALLINT     NOT NULL,
    [activeSkillSlot1] SMALLINT     NOT NULL,
    [RandBuffID]       INT          NOT NULL,
    [LeftTime]         INT          NOT NULL,
    [LockedLeftTime]   INT          NOT NULL,
    [Characters0]      INT          NOT NULL,
    [Characters1]      INT          NOT NULL,
    [Characters2]      INT          NOT NULL,
    [Characters3]      INT          NOT NULL,
    [Characters4]      INT          NOT NULL,
    [EquipItem0]       INT          NOT NULL,
    [EquipItem1]       INT          NOT NULL,
    [EquipItem2]       INT          NOT NULL,
    [EquipItem3]       INT          NOT NULL
);







