#ifndef _SHAREMEMORYKEY_H_
#define _SHAREMEMORYKEY_H_

//¹²ÏíÄÚ´æµÄkey
enum ShareMemoryKey
{
	SMKEY_DATAAGENT_PLAYER = 1,
    SMKEY_WORLDACCOUNT,
    SMKEY_TEAM,
    SMKEY_COPYMAP,
	SMKEY_STALLLIST,
};

#endif /*_SHAREMEMORYKEY_H_*/