/*CREATE PROC [dbo].[Sp_GetDataOne]
(
	@FileName			VARCHAR(200),
	@TableName			VARCHAR(200),
	@FIELDTERMINATOR	VARCHAR(10) = '	'
)
AS
BEGIN
	DECLARE @SQL VARCHAR(MAX)
	SELECT @SQL = ''
	SELECT @SQL = 'BULK INSERT '+@TableName+CHAR(13)+
	'FROM '''+@FileName+''''+CHAR(13)+
	'WITH ('+CHAR(13)+
			'FIELDTERMINATOR ='''+ @FIELDTERMINATOR+''','+CHAR(13)+
			'ROWTERMINATOR =''\n'','+CHAR(13)+
			'TABLOCK' + CHAR(13)+')'
	PRINT @SQL
	ALTER DATABASE CHAR	SET RECOVERY BULK_LOGGED
	EXEC (@SQL)
	ALTER DATABASE CHAR	SET RECOVERY FULL
END*/